from tkinter import *
from tkinter import ttk
import os
from PIL import ImageTk,Image


def user_not_found():
    global user_not_found_screen
    user_not_found_screen = Toplevel(login_screen)
    user_not_found_screen.title("Success")
    user_not_found_screen.geometry("150x100")
    Label(user_not_found_screen, text="User Not Found").pack()
    Button(user_not_found_screen, text="OK", command=delete_user_not_found_screen).pack()
    
    
def login_sucess():
    global login_success_screen
    login_success_screen = Toplevel(login_screen)
    login_success_screen.title("Success")
    login_success_screen.geometry("150x100")
    Label(login_success_screen, text="Login Success").pack()
    Button(login_success_screen, text="OK", command=delete_login_success).pack()
    
def password_not_recognised():
    global password_not_recog_screen
    password_not_recog_screen = Toplevel(login_screen)
    password_not_recog_screen.title("Success")
    password_not_recog_screen.geometry("150x100")
    Label(password_not_recog_screen, text="Invalid Password ").pack()
    Button(password_not_recog_screen, text="OK", command=delete_password_not_recognised).pack()

def delete_login_success():
    login_success_screen.destroy()

    
def delete_password_not_recognised():
    password_not_recog_screen.destroy()


def delete_user_not_found_screen():
    user_not_found_screen.destroy()
    
def login_verify():
    username1 = username_verify.get()
    password1 = password_verify.get()
    username_login_entry.delete(0, END)
    password_login_entry.delete(0, END)
 
    list_of_files = os.listdir()
    if username1 in list_of_files:
        file1 = open(username1, "r")
        verify = file1.read().splitlines()
        if password1 in verify:
            login_sucess()
 
        else:
            password_not_recognised()
 
    else:
        user_not_found()
        
def posted_job():
    page = Toplevel(main_screen)
    page.title("Welcome!!Hire best talent")
    page.geometry("1100x750")
    C1 = Canvas(page, bg="green", height=1100, width=750)
    C1.pack()
    L1 = Label(page, text="You Posted a job!!",width="18",bg="green", height="2", font=("Calibri", 55,"bold"))
    L1.place(in_ = C1, relx = 0.9, rely = 0.05, anchor = NE)
    B1 = Button(page, text="HOME", height="2", width="15",activebackground="#00A508",command = recuiter_homepage)
    B1.place(in_ = C1, relx = 0.5, rely = 0.5, anchor = CENTER)
    
    
    
def post_job():
    page = Toplevel(main_screen)
    page.title("Welcome!!Hire best talent")
    page.geometry("1100x750")
    C1 = Canvas(page, bg="green", height=1100, width=750)
    C1.pack()
    C2 = Canvas(page, bg="#116FEE", height=300, width=600)
    C2.place(in_ = C1,relx = 0.46,rely =0.27,anchor = CENTER )
    L1 = Label(page, text="Job Title",width="10",bg="#116FEE", height="1", font=("Calibri",25,"bold"))
    L1.place(in_ = C2, relx = 0.15, rely = 0.12, anchor = CENTER)
    T1= Text(page, height = 1, width = 20,font=("Calibri", 20))
    INPUT1 = T1.get("1.0", "end-1c") 
    print(INPUT1) 
    T1.place(in_ = C2, relx = 0.6, rely = 0.09, anchor = CENTER)
    L2 = Label(page, text="Location",width="10",bg="#116FEE", height="1", font=("Calibri",25,"bold"))
    L2.place(in_ = C2, relx = 0.15, rely = 0.27, anchor = CENTER)
    T2= Text(page, height = 1, width = 20,font=("Calibri", 20))
    INPUT2 = T2.get("1.0", "end-1c") 
    print(INPUT2)
    T2.place(in_ = C2, relx = 0.6, rely = 0.27, anchor = CENTER)
    L3 = Label(page, text="Description",width="10",bg="#116FEE", height="1", font=("Calibri",25,"bold"))
    L3.place(in_ = C2, relx = 0.17, rely = 0.47, anchor = CENTER)
    T3= Text(page, height = 4, width = 35,font=("Calibri", 20))
    INPUT3 = T3.get("1.0", "end-1c") 
    print(INPUT3)
    T3.place(in_ = C2, relx = 0.45, rely = 0.77, anchor = CENTER)
    C3 = Canvas(page, bg="#116FEE", height=150, width=600)
    C3.place(in_ = C1,relx = 0.46,rely =0.67,anchor = CENTER )
    L4 = Label(page, text="No. of Vacancy",width="10",bg="#116FEE", height="1", font=("Calibri",25,"bold"))
    L4.place(in_ = C3, relx = 0.19, rely = 0.17, anchor = CENTER)
    T4= Text(page, height = 1, width = 10,font=("Calibri", 20))
    INPUT4 = T4.get("1.0", "end-1c") 
    print(INPUT4) 
    T4.place(in_ = C3, relx = 0.6, rely = 0.17, anchor = CENTER)
    L5 = Label(page, text="Salary",width="10",bg="#116FEE", height="1", font=("Calibri",25,"bold"))
    L5.place(in_ = C3, relx = 0.19, rely = 0.5, anchor = CENTER)
    sal = ttk.Combobox(page, width = 15)
    sal['values'] = ('Not Disclosed',)
    sal.place(in_ = C3, relx = 0.48,rely = 0.5)
    B1 = Button(page, text="POST", height="2", width="15",activebackground="#00A508",command = posted_job)
    B1.place(in_ = C1, relx = 0.2, rely = 0.86, anchor = CENTER)
    B2 = Button(page, text="CANCEL", height="2", width="15",activebackground="#00A508",command = recuiter_homepage)
    B2.place(in_ = C1, relx = 0.5, rely = 0.86, anchor = CENTER)
   
    
    
    
def view_app():
    page = Toplevel(main_screen)
    page.title("Welcome!!Hire best talent")
    page.geometry("1100x750")
    C1 = Canvas(page, bg="green", height=1100, width=750)
    C1.pack()
    L = Label(page, text="View Applications",width="15",bg="green", height="1", font=("Calibri", 25,"bold"))
    L.place(in_ = C1, relx = 0.2, rely = 0.05, anchor = CENTER)
    C2 = Canvas(page, bg="#00A508", height=100, width=600)
    C2.place(in_ = C1,relx = 0.46,rely =0.2,anchor = CENTER )
    L3 = Label(page, text="Reliance Infocom",width="11",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L3.place(in_ = C2, relx = 0.12, rely = 0.2, anchor = CENTER)
    L4 = Label(page, text="Job Title:",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.072, rely = 0.43, anchor = CENTER)
    L5 = Label(page, text="Network Engineer",width="13",bg="#00A508", height="1", font=("Calibri", 15))
    L5.place(in_ = C2, relx = 0.28, rely = 0.42, anchor = CENTER)
    L4 = Label(page, text="Eligibility :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.082, rely = 0.66, anchor = CENTER)
    L6 = Label(page, text="B.Tech/M.Tech(Fresher)",width="16",bg="#00A508", height="1", font=("Calibri", 15))
    L6.place(in_ = C2, relx = 0.32, rely = 0.7, anchor = CENTER)
    L7 = Label(page, text="Location :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L7.place(in_ = C2, relx = 0.57, rely = 0.43, anchor = CENTER)
    L8 = Label(page, text="Bangalore",width="8",bg="#00A508", height="1", font=("Calibri", 15))
    L8.place(in_ = C2, relx = 0.73, rely = 0.42, anchor = CENTER)
    L9 = Label(page, text="Salary:",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L9.place(in_ = C2, relx = 0.57, rely = 0.66, anchor = CENTER)
    L10 = Label(page, text="Not Disclosed",width="15",bg="#00A508", height="1", font=("Calibri", 15))
    L10.place(in_ = C2, relx = 0.75, rely = 0.66, anchor = CENTER)
    C3 = Canvas(page, bg="#116FEE", height=50, width=600)
    C3.place(in_ = C1,relx = 0.46,rely =0.35,anchor = CENTER )
    L11 = Label(page, text="B.Tech(CSE)",width="12",bg="#116FEE", height="1", font=("Calibri", 15,"bold"))
    L11.place(in_ = C3, relx = 0.12, rely = 0.29, anchor = CENTER)
    L12 = Label(page, text="Hitesh Tripati",width="12",bg="#116FEE", height="1", font=("Calibri", 15,"bold"))
    L12.place(in_ = C3, relx = 0.32, rely = 0.29, anchor = CENTER)
    B2 = Button(page, text="Confirm", height="1", width="5",activebackground="#00A508")
    B2.place(in_ = C3, relx = 0.7, rely = 0.4, anchor = CENTER)
    B2 = Button(page, text="Cancel", height="1", width="5",activebackground="#00A508")
    B2.place(in_ = C3, relx = 0.9, rely = 0.4, anchor = CENTER)
    C4 = Canvas(page, bg="#116FEE", height=50, width=600)
    C4.place(in_ = C1,relx = 0.46,rely =0.45,anchor = CENTER )
    L11 = Label(page, text="MBA",width="12",bg="#116FEE", height="1", font=("Calibri", 15,"bold"))
    L11.place(in_ = C4, relx = 0.12, rely = 0.29, anchor = CENTER)
    L12 = Label(page, text="Karan Singh",width="12",bg="#116FEE", height="1", font=("Calibri", 15,"bold"))
    L12.place(in_ = C4, relx = 0.32, rely = 0.29, anchor = CENTER)
    B2 = Button(page, text="Confirm", height="1", width="5",activebackground="#00A508")
    B2.place(in_ = C4, relx = 0.7, rely = 0.4, anchor = CENTER)
    B2 = Button(page, text="Cancel", height="1", width="5",activebackground="#00A508")
    B2.place(in_ = C4, relx = 0.9, rely = 0.4, anchor = CENTER)
    C5 = Canvas(page, bg="#00A508", height=100, width=600)
    C5.place(in_ = C1,relx = 0.46,rely =0.64,anchor = CENTER )
    L3 = Label(page, text="Reliance Infocom",width="11",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L3.place(in_ = C5, relx = 0.12, rely = 0.2, anchor = CENTER)
    L4 = Label(page, text="Job Title:",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C5, relx = 0.072, rely = 0.43, anchor = CENTER)
    L5 = Label(page, text="Software Engineer",width="13",bg="#00A508", height="1", font=("Calibri", 15))
    L5.place(in_ = C5, relx = 0.28, rely = 0.42, anchor = CENTER)
    L4 = Label(page, text="Eligibility :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C5, relx = 0.082, rely = 0.66, anchor = CENTER)
    L6 = Label(page, text="B.Tech/M.Tech(Fresher)",width="16",bg="#00A508", height="1", font=("Calibri", 15))
    L6.place(in_ = C5, relx = 0.32, rely = 0.7, anchor = CENTER)
    L7 = Label(page, text="Location :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L7.place(in_ = C5, relx = 0.57, rely = 0.43, anchor = CENTER)
    L8 = Label(page, text="Bangalore",width="8",bg="#00A508", height="1", font=("Calibri", 15))
    L8.place(in_ = C5, relx = 0.73, rely = 0.42, anchor = CENTER)
    L9 = Label(page, text="Salary:",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L9.place(in_ = C5, relx = 0.57, rely = 0.66, anchor = CENTER)
    L10 = Label(page, text="Not Disclosed",width="15",bg="#00A508", height="1", font=("Calibri", 15))
    L10.place(in_ = C5, relx = 0.75, rely = 0.66, anchor = CENTER)
    C6 = Canvas(page, bg="#116FEE", height=50, width=600)
    C6.place(in_ = C1,relx = 0.46,rely =0.8,anchor = CENTER )
    L11 = Label(page, text="MBA",width="12",bg="#116FEE", height="1", font=("Calibri", 15,"bold"))
    L11.place(in_ = C6, relx = 0.12, rely = 0.29, anchor = CENTER)
    L12 = Label(page, text="Anisha Singh",width="12",bg="#116FEE", height="1", font=("Calibri", 15,"bold"))
    L12.place(in_ = C6, relx = 0.32, rely = 0.29, anchor = CENTER)
    B2 = Button(page, text="Confirm", height="1", width="5",activebackground="#00A508")
    B2.place(in_ = C6, relx = 0.7, rely = 0.4, anchor = CENTER)
    B2 = Button(page, text="Cancel", height="1", width="5",activebackground="#00A508")
    B2.place(in_ = C6, relx = 0.9, rely = 0.4, anchor = CENTER)
    B3 = Button(page, text="HOME", height="2", width="15",activebackground="#00A508",command = recuiter_homepage)
    B3.place(in_ = C1, relx = 0.2, rely = 0.9, anchor = CENTER)
    
    
    

def recuiter_homepage():
    page = Toplevel(main_screen)
    page.title("Welcome!!Hire best talent")
    page.geometry("1100x750")
    C1 = Canvas(page, bg="green", height=1100, width=750)
    C1.pack()
    L1 = Label(page, text="Welcome!",width="8",bg="green", height="2", font=("Calibri", 55,"bold"))
    L1.place(in_ = C1, relx = 0.4, rely = 0.05, anchor = NE)
    L2 = Label(page, text="Jobs Your company posted",width="20",bg="green", height="2", font=("Calibri", 25,"bold"))
    L2.place(in_ = C1, relx = 0.27, rely = 0.38, anchor = CENTER)
    B1 = Button(page, text="POST JOB", height="2", width="15",activebackground="#00A508",command = post_job)
    B1.place(in_ = C1, relx = 0.17, rely = 0.3, anchor = CENTER)
    B2 = Button(page, text="VIEW APPLICATIONS", height="2", width="15",activebackground="#00A508",command = view_app)
    B2.place(in_ = C1, relx = 0.5, rely = 0.3, anchor = CENTER)
    B3 = Button(page, text="LOGOUT", height="2", width="15",activebackground="#00A508",command = recuiter_login)
    B3.place(in_ = C1, relx = 0.8, rely = 0.3, anchor = CENTER)
    C2 = Canvas(page, bg="#00A508", height=100, width=600)
    C2.place(in_ = C1,relx = 0.46,rely =0.49,anchor = CENTER )
    L3 = Label(page, text="Reliance Infocom",width="11",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L3.place(in_ = C2, relx = 0.12, rely = 0.2, anchor = CENTER)
    L4 = Label(page, text="Job Title:",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.072, rely = 0.43, anchor = CENTER)
    L5 = Label(page, text="Network Engineer",width="13",bg="#00A508", height="1", font=("Calibri", 15))
    L5.place(in_ = C2, relx = 0.28, rely = 0.42, anchor = CENTER)
    L4 = Label(page, text="Eligibility :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.082, rely = 0.66, anchor = CENTER)
    L6 = Label(page, text="B.Tech/M.Tech(Fresher)",width="16",bg="#00A508", height="1", font=("Calibri", 15))
    L6.place(in_ = C2, relx = 0.32, rely = 0.7, anchor = CENTER)
    L7 = Label(page, text="Location :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L7.place(in_ = C2, relx = 0.57, rely = 0.43, anchor = CENTER)
    L8 = Label(page, text="Bangalore",width="8",bg="#00A508", height="1", font=("Calibri", 15))
    L8.place(in_ = C2, relx = 0.73, rely = 0.42, anchor = CENTER)
    L9 = Label(page, text="Salary:",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L9.place(in_ = C2, relx = 0.57, rely = 0.66, anchor = CENTER)
    L10 = Label(page, text="Not Disclosed",width="15",bg="#00A508", height="1", font=("Calibri", 15))
    L10.place(in_ = C2, relx = 0.75, rely = 0.66, anchor = CENTER)
    B4 = Button(page, text="CANCEL", height="2", width="15",activebackground="#00A508",command = recuiter_login)
    B4.place(in_ = C1, relx = 0.74, rely = 0.61, anchor = CENTER)
    C2 = Canvas(page, bg="#00A508", height=100, width=600)
    C2.place(in_ = C1,relx = 0.46,rely =0.74,anchor = CENTER )
    L3 = Label(page, text="Reliance Infocom",width="11",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L3.place(in_ = C2, relx = 0.12, rely = 0.2, anchor = CENTER)
    L4 = Label(page, text="Job Title:",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.072, rely = 0.43, anchor = CENTER)
    L5 = Label(page, text="Software Engineer",width="13",bg="#00A508", height="1", font=("Calibri", 15))
    L5.place(in_ = C2, relx = 0.28, rely = 0.42, anchor = CENTER)
    L4 = Label(page, text="Eligibility :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.082, rely = 0.66, anchor = CENTER)
    L6 = Label(page, text="B.Tech/M.Tech(Fresher)",width="16",bg="#00A508", height="1", font=("Calibri", 15))
    L6.place(in_ = C2, relx = 0.32, rely = 0.7, anchor = CENTER)
    L7 = Label(page, text="Location :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L7.place(in_ = C2, relx = 0.57, rely = 0.43, anchor = CENTER)
    L8 = Label(page, text="Bangalore",width="8",bg="#00A508", height="1", font=("Calibri", 15))
    L8.place(in_ = C2, relx = 0.73, rely = 0.42, anchor = CENTER)
    L9 = Label(page, text="Salary:",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L9.place(in_ = C2, relx = 0.57, rely = 0.66, anchor = CENTER)
    L10 = Label(page, text="Not Disclosed",width="15",bg="#00A508", height="1", font=("Calibri", 15))
    L10.place(in_ = C2, relx = 0.75, rely = 0.66, anchor = CENTER)
    B4 = Button(page, text="CANCEL", height="2", width="15",activebackground="#00A508",command = recuiter_login)
    B4.place(in_ = C1, relx = 0.74, rely = 0.86, anchor = CENTER)
        
        
        
        
def apply_job():
    page = Toplevel(main_screen)
    page.title("Applied for job!!!")
    page.geometry("1100x750")
    C1 = Canvas(page, bg="green", height=1100, width=750)
    C1.pack()
    L1 = Label(page, text="Congratulations!!",width="18",bg="green", height="2", font=("Calibri", 55,"bold"))
    L1.place(in_ = C1, relx = 0.9, rely = 0.05, anchor = NE)
    L2 = Label(page, text="You applied for the job",width="18",bg="green", height="2", font=("Calibri",30,"bold"))
    L2.place(in_ = C1, relx = 0.7, rely = 0.25, anchor = NE)
    L3 = Label(page, text="You will be contacted through E-mail for further Process",width="40",bg="green", height="2", font=("Calibri",20,"bold"))
    L3.place(in_ = C1, relx = 0.85, rely = 0.35, anchor = NE)
    B1 = Button(page, text="LOGOUT", height="2", width="15",activebackground="#00A508",command = candidate_login)
    B1.place(in_ = C1, relx = 0.25, rely = 0.56, anchor = CENTER)
    B2 = Button(page, text="HOMEPAGE", height="2", width="15",activebackground="#00A508",command = candidate_homepage)
    B2.place(in_ = C1, relx = 0.65, rely = 0.56, anchor = CENTER)
    
   
    
    
    
    

def candidate_homepage():
    home_page = Toplevel(main_screen)
    home_page.title("Register yourself to get hired by best companies in the country")
    home_page.geometry("1100x750")
    Label(home_page,text="Get hired by best companies in the country", bg="green", width="300", height="2", font=("Calibri", 21))
    C1 = Canvas(home_page, bg="green", height=1100, width=750)
    C1.pack()
    L1 = Label(home_page, text="Welcome!",width="10",bg="green", height="2", font=("Calibri", 55,"bold"))
    L1.place(in_ = C1, relx = 0.5, rely = 0.05, anchor = NE)
    L2 = Label(home_page, text="Apply for the roles in leading companies of India",width="35",bg="green", height="2", font=("Calibri", 25,"bold"))
    L2.place(in_ = C1, relx = 0.45, rely = 0.3, anchor = CENTER)
    C2 = Canvas(home_page, bg="#00A508", height=100, width=600)
    C2.place(in_ = C1,relx = 0.45,rely =0.4,anchor = CENTER )
    L3 = Label(home_page, text="Reliance Infocom",width="11",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L3.place(in_ = C2, relx = 0.12, rely = 0.2, anchor = CENTER)
    L4 = Label(home_page, text="Job Title:",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.072, rely = 0.43, anchor = CENTER)
    L5 = Label(home_page, text="Network Engineer",width="13",bg="#00A508", height="1", font=("Calibri", 15))
    L5.place(in_ = C2, relx = 0.28, rely = 0.42, anchor = CENTER)
    L4 = Label(home_page, text="Eligibility :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L4.place(in_ = C2, relx = 0.082, rely = 0.66, anchor = CENTER)
    L6 = Label(home_page, text="B.Tech/M.Tech(Fresher)",width="16",bg="#00A508", height="1", font=("Calibri", 15))
    L6.place(in_ = C2, relx = 0.32, rely = 0.7, anchor = CENTER)
    L7 = Label(home_page, text="Location :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L7.place(in_ = C2, relx = 0.57, rely = 0.43, anchor = CENTER)
    L8 = Label(home_page, text="Bangalore",width="8",bg="#00A508", height="1", font=("Calibri", 15))
    L8.place(in_ = C2, relx = 0.73, rely = 0.42, anchor = CENTER)
    L9 = Label(home_page, text="Salary:",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L9.place(in_ = C2, relx = 0.57, rely = 0.66, anchor = CENTER)
    L10 = Label(home_page, text="Not Disclosed",width="15",bg="#00A508", height="1", font=("Calibri", 15))
    L10.place(in_ = C2, relx = 0.75, rely = 0.66, anchor = CENTER)
    B1 = Button(home_page, text="APPLY", height="2", width="15",activebackground="#00A508",command = apply_job)
    B1.place(in_ = C1, relx = 0.74, rely = 0.51, anchor = CENTER)
    C3 = Canvas(home_page, bg="#00A508", height=100, width=600)
    C3.place(in_ = C1,relx = 0.45,rely =0.65,anchor = CENTER )
    L11 = Label(home_page, text="Atlassian",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L11.place(in_ = C3, relx = 0.08, rely = 0.2, anchor = CENTER)
    L12 = Label(home_page, text="Job Title:",width="6",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L12.place(in_ = C3, relx = 0.072, rely = 0.43, anchor = CENTER)
    L13 = Label(home_page, text="Hiring Manager",width="13",bg="#00A508", height="1", font=("Calibri", 15))
    L13.place(in_ = C3, relx = 0.28, rely = 0.42, anchor = CENTER)
    L14 = Label(home_page, text="Eligibility :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L14.place(in_ = C3, relx = 0.082, rely = 0.66, anchor = CENTER)
    L15 = Label(home_page, text="MBA(5Y exp.)",width="16",bg="#00A508", height="1", font=("Calibri", 15))
    L15.place(in_ = C3, relx = 0.28, rely = 0.7, anchor = CENTER)
    L16 = Label(home_page, text="Location :",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L16.place(in_ = C3, relx = 0.57, rely = 0.43, anchor = CENTER)
    L17 = Label(home_page, text="Hyderabad",width="8",bg="#00A508", height="1", font=("Calibri", 15))
    L17.place(in_ = C3, relx = 0.73, rely = 0.42, anchor = CENTER)
    L18 = Label(home_page, text="Salary:",width="8",bg="#00A508", height="1", font=("Calibri", 15,"bold"))
    L18.place(in_ = C3, relx = 0.57, rely = 0.66, anchor = CENTER)
    L19 = Label(home_page, text="Not Disclosed",width="15",bg="#00A508", height="1", font=("Calibri", 15))
    L19.place(in_ = C3, relx = 0.75, rely = 0.66, anchor = CENTER)
    B2 = Button(home_page, text="APPLY", height="2", width="15",activebackground="#00A508",command = apply_job)
    B2.place(in_ = C1, relx = 0.74, rely = 0.76, anchor = CENTER)
    B3 = Button(home_page, text="LOGOUT", height="2", width="15",activebackground="#00A508",command = candidate_login)
    B3.place(in_ = C1, relx = 0.2, rely = 0.86, anchor = CENTER)
        
def candidate_login():
    global login_screen_c
    login_screen_c = Toplevel(main_screen)
    login_screen_c.title("Login")
    login_screen_c.geometry("1100x750")
    Label(login_screen_c, text="Please enter details below to login").pack()
    Label(login_screen_c, text="").pack()
 
    global username_verify
    global password_verify_c
 
    username_verify = StringVar()
    password_verify = StringVar()
 
    global username_login_entry
    global password_login_entry
 
    Label(login_screen_c, text="Username * ").pack()
    username_login_entry = Entry(login_screen_c, textvariable = username_verify)
    username_login_entry.pack()
    Label(login_screen_c, text="Password * ").pack()
    password_login_entry = Entry(login_screen_c, show= '*')
    password_login_entry.pack()
    Button(login_screen_c, text="Login", width=10, height=1, command = candidate_homepage).pack()

def recuiter_login():
    global login_screen_r
    login_screen_r = Toplevel(main_screen)
    login_screen_r.title("Login")
    login_screen_r.geometry("1100x750")
    Label(login_screen_r, text="Please enter details below to login").pack()
    Label(login_screen_r, text="").pack()
 
    global username_verify
    global password_verify
 
    username_verify = StringVar()
    password_verify = StringVar()
 
    global username_login_entry
    global password_login_entry
 
    Label(login_screen_r, text="Your Company's Name * ").pack()
    username_login_entry = Entry(login_screen_r, textvariable=username_verify)
    username_login_entry.pack()
    Label(login_screen_r, text="Password * ").pack()
    password_login_entry = Entry(login_screen_r, textvariable=password_verify, show= '*')
    password_login_entry.pack()
    Button(login_screen_r, text="Login", width=10, height=1, command = recuiter_homepage).pack()

    
def second_landing_for_candidate():
    global login_page_candidate
    login_page_candidate = Toplevel(main_screen)
    login_page_candidate.geometry("1100x750")
    Label(login_page_candidate, text="Select Your Choice", bg="green", width="300", height="2", font=("Calibri", 13)).pack()
    Button(login_page_candidate, text="Login", height="2", width="30", command = candidate_login).pack()
    Button(login_page_candidate, text="Register", height="2", width="30", command = candidate_register).pack()
    

def recuiter_complete_register():
    register_page = Toplevel(main_screen)
    register_page.title("Registeration Complete")
    register_page.geometry("1100x750")
    Label(register_page,text="Registeration Complete.Login", bg="#cce0ff", width="300", height="2", font=("Calibri", 21)).pack()
    B1 = Button(register_page, text="LOGIN", height="2", width="30", background="#99c2ff",command = second_landing_for_recuiter).pack()
    
    
def fourth_candidate_register():
    recuiter_register_page = Toplevel(main_screen)
    recuiter_register_page.title("Register yourself to get hired by best companies in the country")
    recuiter_register_page.geometry("1100x750")
    Label(recuiter_register_page,text="Register yourself to get hired by best companies in the country", bg="#cce0ff", width="300", height="2", font=("Calibri", 21))
    C1 = Canvas(recuiter_register_page, bg="#99c2ff", height=1100, width=750)
    C1.pack()
    L1 = Label(recuiter_register_page, text="Email:",width="17",bg="#99c2ff", height="2", font=("Calibri", 20))
    L1.place(in_ = C1, relx = 0.35, rely = 0.05, anchor = NE)
    T1= Text(recuiter_register_page, height = 1, width = 20,font=("Calibri", 20))
    INPUT1 = T1.get("1.0", "end-1c") 
    print(INPUT1) 
    T1.place(in_ = C1, relx = 0.6, rely = 0.095, anchor = CENTER)
    L2 = Label(recuiter_register_page, text="Username:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L2.place(in_ = C1, relx = 0.37, rely = 0.15, anchor = NE)
    T2= Text(recuiter_register_page, height = 1, width = 20,font=("Calibri", 20))
    INPUT2 = T2.get("1.0", "end-1c") 
    print(INPUT2) 
    T2.place(in_ = C1, relx = 0.6, rely = 0.2, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="Create Password: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.37, rely = 0.27, anchor = NE)
    password_login_entry = Entry(recuiter_register_page, show = '*')
    password_login_entry.place(in_ = C1, relx = 0.68, rely = 0.3, anchor = NE)
    chk = Checkbutton(recuiter_register_page, text='I agree with the terms and conditions', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk.place(in_ = C1, relx = 0.05, rely = 0.47, anchor = SW)
    B1 = Button(recuiter_register_page, text="REGISTER", height="2", width="30",background="#99c2ff",command = candidate_complete_register)
    B1.place(in_ = C1, relx = 0.5, rely = 0.57, anchor = CENTER)
    
    
    
    

def third_candidate_register():
    recuiter_register_page = Toplevel(main_screen)
    recuiter_register_page.title("Register yourself to get hired by best companies in the country")
    recuiter_register_page.geometry("1100x750")
    Label(recuiter_register_page,text="Register yourself to get hired by best companies in the country", bg="#cce0ff", width="300", height="2", font=("Calibri", 21))
    C1 = Canvas(recuiter_register_page, bg="#99c2ff", height=1100, width=750)
    C1.pack()
    L1 = Label(recuiter_register_page, text="Programme is: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L1.place(in_ = C1, relx = 0.37, rely = 0.05, anchor = NE)
    board = ttk.Combobox(recuiter_register_page, width = 15)
    board['values'] = ('ongoing','passed')
    board.place(in_ = C1, relx = 0.43,rely = 0.07)
    L2 = Label(recuiter_register_page, text="CGPA or Grade achieved",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L2.place(in_ = C1, relx = 0.37, rely = 0.12, anchor = NE)
    T1= Text(recuiter_register_page, height = 1, width = 5,font=("Calibri", 20))
    INPUT1 = T1.get("1.0", "end-1c") 
    print(INPUT1) 
    T1.place(in_ = C1, relx = 0.48, rely = 0.15, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="Co-circular Activities:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.40, rely = 0.20, anchor = NE)
    T2= Text(recuiter_register_page, height = 3, width = 20,font=("Calibri", 20))
    INPUT2 = T2.get("1.0", "end-1c") 
    print(INPUT2) 
    T2.place(in_ = C1, relx = 0.62, rely = 0.28, anchor = CENTER)
    L4 = Label(recuiter_register_page, text="Project Details:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L4.place(in_ = C1, relx = 0.36, rely = 0.44, anchor = NE)
    T3= Text(recuiter_register_page, height = 3, width = 20,font=("Calibri", 20))
    INPUT3 = T3.get("1.0", "end-1c") 
    print(INPUT3) 
    T3.place(in_ = C1, relx = 0.62, rely = 0.48, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="YOU ARE SKILLED IN:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.40, rely = 0.55, anchor = NE)
    chk = Checkbutton(recuiter_register_page, text='Hiring management', bg="#99c2ff",onvalue = 1, offvalue = 0)
    print()
    chk.place(in_ = C1, relx = 0.1, rely = 0.65, anchor = SW)
    chk1 = Checkbutton(recuiter_register_page, text='Software Development', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk1.place(in_ = C1, relx = 0.1, rely = 0.69, anchor = SW)
    chk2 = Checkbutton(recuiter_register_page, text='Production process', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk2.place(in_ = C1, relx = 0.1, rely = 0.73, anchor = SW)
    chk3 = Checkbutton(recuiter_register_page, text='Technician ',  bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk3.place(in_ = C1, relx = 0.1, rely = 0.77, anchor = SW)
    chk4= Checkbutton(recuiter_register_page, text='Software Management', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk4.place(in_ = C1, relx = 0.5, rely = 0.65, anchor = SW)
    chk5 = Checkbutton(recuiter_register_page, text='Site reliability Engineering', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk5.place(in_ = C1, relx = 0.5, rely = 0.69, anchor = SW)
    chk6 = Checkbutton(recuiter_register_page, text='workforce', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk6.place(in_ = C1, relx = 0.5, rely = 0.73, anchor = SW)
    chk7 = Checkbutton(recuiter_register_page, text='Field Experts', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk7.place(in_ = C1, relx = 0.5, rely = 0.77, anchor = SW)
    chk8 = Checkbutton(recuiter_register_page, text='Marketing',  bg="#99c2ff", onvalue = 1, offvalue = 0)
    chk8.place(in_ = C1, relx = 0.5, rely = 0.81, anchor = SW)
    B1 = Button(recuiter_register_page, text="NEXT", height="2", width="30",background="#99c2ff",command = fourth_candidate_register)
    B1.place(in_ = C1, relx = 0.5, rely = 0.9, anchor = CENTER)
    
    
    
    
def second_candidate_register():
    recuiter_register_page = Toplevel(main_screen)
    recuiter_register_page.title("Register yourself to get hired by best companies in the country")
    recuiter_register_page.geometry("1100x750")
    Label(recuiter_register_page,text="Register yourself to get hired by best companies in the country", bg="#cce0ff", width="300", height="2", font=("Calibri", 21)).pack()
    C1 = Canvas(recuiter_register_page, bg="#99c2ff", height=1100, width=750)
    C1.pack()
    L1 = Label(recuiter_register_page, text="10th School Name: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L1.place(in_ = C1, relx = 0.37, rely = 0.05, anchor = NE)
    T1= Text(recuiter_register_page, height = 1, width = 20,font=("Calibri", 20))
    INPUT1 = T1.get("1.0", "end-1c") 
    print(INPUT1) 
    T1.place(in_ = C1, relx = 0.6, rely = 0.1, anchor = CENTER)
    L2 = Label(recuiter_register_page, text="12th details: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L2.place(in_ = C1, relx = 0.37, rely = 0.15, anchor = NE)
    board = ttk.Combobox(recuiter_register_page, width = 15)
    board['values'] = ('ICSE','CBSE','State Board')
    board.place(in_ = C1, relx = 0.47,rely = 0.28)
    L3 = Label(recuiter_register_page, text="Board : ",width="8",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.25, rely = 0.25, anchor = NE)
    L4 = Label(recuiter_register_page, text="12th Percentage: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L4.place(in_ = C1, relx = 0.37, rely = 0.35, anchor = NE)
    T2= Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT2 = T2.get("1.0", "end-1c") 
    print(INPUT2) 
    T2.place(in_ = C1, relx = 0.6, rely = 0.39, anchor = CENTER)
    L4 = Label(recuiter_register_page, text="12th School Name: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L4.place(in_ = C1, relx = 0.37, rely = 0.47, anchor = NE)
    T3= Text(recuiter_register_page, height = 1, width = 20,font=("Calibri", 20))
    INPUT3 = T3.get("1.0", "end-1c") 
    print(INPUT3) 
    T3.place(in_ = C1, relx = 0.6, rely = 0.5, anchor = CENTER)
    L5 = Label(recuiter_register_page, text="Higher Education details :",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L5.place(in_ = C1, relx = 0.37, rely = 0.55, anchor = NE)
    L6 = Label(recuiter_register_page, text="Leave that do not apply:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L6.place(in_ = C1, relx = 0.5, rely = 0.63, anchor = NE)
    L7 = Label(recuiter_register_page, text="Programme Name:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L7.place(in_ = C1, relx = 0.37, rely = 0.7, anchor = NE)
    T4= Text(recuiter_register_page, height = 1, width = 20,font=("Calibri", 20))
    INPUT4 = T4.get("1.0", "end-1c") 
    print(INPUT4) 
    T4.place(in_ = C1, relx = 0.6, rely = 0.75, anchor = CENTER)
    B1 = Button(recuiter_register_page, text="NEXT", height="2", width="30",background="#99c2ff",command = third_candidate_register)
    B1.place(in_ = C1, relx = 0.5, rely = 0.9, anchor = CENTER)
    
    
def candidate_register():
    recuiter_register_page = Toplevel(main_screen)
    recuiter_register_page.title("Register yourself to get hired by best companies in the country")
    recuiter_register_page.geometry("1100x750")
    Label(recuiter_register_page,text="Register yourself to get hired by best companies in the country", bg="#cce0ff", width="300", height="2", font=("Calibri", 21)).pack()
    C1 = Canvas(recuiter_register_page, bg="#99c2ff", height=1100, width=750)
    C1.pack()
    L1 = Label(recuiter_register_page, text="YOUR NAME ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L1.place(in_ = C1, relx = 0.36, rely = 0.03, anchor = NE)
    T1 = Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT = T1.get("1.0", "end-1c") 
    print(INPUT) 
    T1.place(in_ = C1, relx = 0.6, rely = 0.07, anchor = CENTER)
    L2 = Label(recuiter_register_page, text="YOUR AADHAR NO. FOR\n INDENTITY PROOF:",width="24",bg="#99c2ff", height="2", font=("Calibri", 20))
    L2.place(in_ = C1, relx = 0.45, rely = 0.14, anchor = NE)
    T2= Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT1 = T2.get("1.0", "end-1c") 
    print(INPUT1) 
    T2.place(in_ = C1, relx = 0.6, rely = 0.2, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="TELL US SOMETHING ABOUT YOURSELF:",width="30",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.6, rely = 0.25, anchor = NE)
    T3= Text(recuiter_register_page, height = 5, width = 50,font=("Calibri", 20))
    INPUT3 = T3.get("1.0", "end-1c") 
    print(INPUT3)
    T3.place(in_ = C1, relx = 0.5, rely = 0.42, anchor = CENTER)
    

    L4 = Label(recuiter_register_page, text="10th details: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L4.place(in_ = C1, relx = 0.37, rely = 0.55, anchor = NE)
    board = ttk.Combobox(recuiter_register_page, width = 15)
    board['values'] = ('ICSE','CBSE','State Board')
    board.place(in_ = C1, relx = 0.47,rely = 0.65)
    L5 = Label(recuiter_register_page, text="Board : ",width="8",bg="#99c2ff", height="2", font=("Calibri", 20))
    L5.place(in_ = C1, relx = 0.25, rely = 0.62, anchor = NE)
    L4 = Label(recuiter_register_page, text="10th Percentage: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L4.place(in_ = C1, relx = 0.37, rely = 0.7, anchor = NE)
    T4= Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT3 = T4.get("1.0", "end-1c") 
    print(INPUT3) 
    T4.place(in_ = C1, relx = 0.6, rely = 0.75, anchor = CENTER)
    B1 = Button(recuiter_register_page, text="NEXT", height="2", width="30",background="#99c2ff",command = second_candidate_register)
    B1.place(in_ = C1, relx = 0.5, rely = 0.9, anchor = CENTER)
    
    
def candidate_complete_register():
    register_page = Toplevel(main_screen)
    register_page.title("Registeration Complete")
    register_page.geometry("1100x750")
    Label(register_page,text="Registeration Complete.Login", bg="#cce0ff", width="300", height="2", font=("Calibri", 21)).pack()
    B1 = Button(register_page, text="LOGIN", height="2", width="30",background="#99c2ff",command = second_landing_for_candidate).pack()
    
    
def next_recuiter_register():
    recuiter_register_page = Toplevel(main_screen)
    recuiter_register_page.title("Register your Company to our Portal")
    recuiter_register_page.geometry("1100x750")
    Label(recuiter_register_page,text="Register Your Company with our Portal and Hire best Talent Across the Country", bg="#cce0ff", width="300", height="2", font=("Calibri", 21)).pack()
    C1 = Canvas(recuiter_register_page, bg="#99c2ff", height=1100, width=750)
    C1.pack()
    L = Label(recuiter_register_page, text="Contact Details:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L.place(in_ = C1, relx = 0.37, rely = 0.01, anchor = NE)
    L1 = Label(recuiter_register_page, text="Public E-mail ID ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L1.place(in_ = C1, relx = 0.37, rely = 0.07, anchor = NE)
    T1 = Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT = T1.get("1.0", "end-1c") 
    print(INPUT) 
    T1.place(in_ = C1, relx = 0.6, rely = 0.11, anchor = CENTER)
    L2 = Label(recuiter_register_page, text="Address and Phone No.: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L2.place(in_ = C1, relx = 0.37, rely = 0.15, anchor = NE)
    T2= Text(recuiter_register_page, height = 5, width = 15,font=("Calibri", 20))
    INPUT1 = T2.get("1.0", "end-1c") 
    print(INPUT1) 
    T2.place(in_ = C1, relx = 0.6, rely = 0.25, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="Create Password: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.37, rely = 0.35, anchor = NE)
    password_login_entry = Entry(recuiter_register_page,show= '*')
    password_login_entry.place(in_ = C1, relx = 0.73, rely = 0.37, anchor = NE)
    chk = Checkbutton(recuiter_register_page, text='My Company agrees with the terms and conditions', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk.place(in_ = C1, relx = 0.05, rely = 0.47, anchor = SW)
    B1 = Button(recuiter_register_page, text="REGISTER", height="2", width="30",background="#99c2ff",command = recuiter_complete_register)
    B1.place(in_ = C1, relx = 0.5, rely = 0.57, anchor = CENTER)
    
def recuiter_register():
    recuiter_register_page = Toplevel(main_screen)
    recuiter_register_page.title("Register your Company to our Portal")
    recuiter_register_page.geometry("1100x750")
    Label(recuiter_register_page,text="Register Your Company with our Portal and Hire best Talent Across the Country", bg="#cce0ff", width="300", height="2", font=("Calibri", 21)).pack()
    C1 = Canvas(recuiter_register_page, bg="#99c2ff", height=1100, width=750)
    C1.pack()
    L1 = Label(recuiter_register_page, text="NAME OF YOUR COMPANY ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L1.place(in_ = C1, relx = 0.37, rely = 0.03, anchor = NE)
    T1 = Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT = T1.get("1.0", "end-1c") 
    print(INPUT) 
    T1.place(in_ = C1, relx = 0.6, rely = 0.07, anchor = CENTER)
    L2 = Label(recuiter_register_page, text="YOUR LICENSE NUMBER: ",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L2.place(in_ = C1, relx = 0.37, rely = 0.15, anchor = NE)
    T2= Text(recuiter_register_page, height = 1, width = 15,font=("Calibri", 20))
    INPUT1 = T2.get("1.0", "end-1c") 
    print(INPUT1) 
    T2.place(in_ = C1, relx = 0.6, rely = 0.2, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="ABOUT COMPANY:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.36, rely = 0.25, anchor = NE)
    T3= Text(recuiter_register_page, height = 5, width = 50,font=("Calibri", 20))
    INPUT3 = T3.get("1.0", "end-1c") 
    print(INPUT3)
    T3.place(in_ = C1, relx = 0.5, rely = 0.4, anchor = CENTER)
    L3 = Label(recuiter_register_page, text="YOU ARE OPEN FOR:",width="20",bg="#99c2ff", height="2", font=("Calibri", 20))
    L3.place(in_ = C1, relx = 0.36, rely = 0.55, anchor = NE)
    chk = Checkbutton(recuiter_register_page, text='Hiring Managers', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk.place(in_ = C1, relx = 0.1, rely = 0.65, anchor = SW)
    chk1 = Checkbutton(recuiter_register_page, text='Software Development Engineers', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk1.place(in_ = C1, relx = 0.1, rely = 0.69, anchor = SW)
    chk2 = Checkbutton(recuiter_register_page, text='Production Staff', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk2.place(in_ = C1, relx = 0.1, rely = 0.73, anchor = SW)
    chk3 = Checkbutton(recuiter_register_page, text='Technicians',  bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk3.place(in_ = C1, relx = 0.1, rely = 0.77, anchor = SW)
    chk4= Checkbutton(recuiter_register_page, text='Software Managers', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk4.place(in_ = C1, relx = 0.5, rely = 0.65, anchor = SW)
    chk5 = Checkbutton(recuiter_register_page, text='Site reliability Engineers', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk5.place(in_ = C1, relx = 0.5, rely = 0.69, anchor = SW)
    chk6 = Checkbutton(recuiter_register_page, text='Workers', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk6.place(in_ = C1, relx = 0.5, rely = 0.73, anchor = SW)
    chk7 = Checkbutton(recuiter_register_page, text='Field Experts', bg="#99c2ff",onvalue = 1, offvalue = 0)
    chk7.place(in_ = C1, relx = 0.5, rely = 0.77, anchor = SW)
    chk8 = Checkbutton(recuiter_register_page, text='Marketing Leads',  bg="#99c2ff", onvalue = 1, offvalue = 0)
    chk8.place(in_ = C1, relx = 0.5, rely = 0.81, anchor = SW)
    B1 = Button(recuiter_register_page, text="NEXT", height="2", width="30",background="#99c2ff",command = next_recuiter_register)
    B1.place(in_ = C1, relx = 0.5, rely = 0.9, anchor = CENTER)
    
    
    
    
    
def second_landing_for_recuiter():
    global login_page_recuiter
    login_page_recuiter = Toplevel(main_screen)
    login_page_recuiter.geometry("1100x750")
    Label(login_page_recuiter, text="Select Your Choice", bg="green", width="300", height="2", font=("Calibri", 13)).pack()
    Button(login_page_recuiter, text="Login", height="2", width="30", command = recuiter_login).pack()
    Button(login_page_recuiter, text="Register", height="2", width="30", command = recuiter_register).pack()
    
def main_account_screen():
    global main_screen
    main_screen = Tk()
    main_screen.geometry("1100x750")
    main_screen.title("XYZ JOB PORTAL")
    Label(text="SELECT WHAT YOU WANT TO DO", bg="green", width="300", height="2", font=("Calibri", 13)).pack()
    C = Canvas(main_screen, bg="green", height=600, width=400)
    b1 = Button(main_screen, text="YOU ARE RECUITER", height="2", width="30", activebackground = "green", background = "white",command = second_landing_for_recuiter)
    b2 = Button(main_screen, text="YOU WANT TO APPLY", height="2", width="30",command = second_landing_for_candidate)
    C.place( relx = 0.5, rely = 0.5, anchor = CENTER)
    b2.place(in_ = C, relx = 0.5, rely = 0.6, anchor = CENTER) 
    b1.place(in_ = C, relx = 0.5, rely = 0.4, anchor = CENTER)
    main_screen.mainloop()
  
 
main_account_screen()